export const GOOGLE_PLACES_API_KEY = 'AIzaSyBf9kr2Wkp7_LbWubptAdEyDhNnUdMV6iI';
export const GOOGLE_MAPS_APIKEY = 'AIzaSyBf9kr2Wkp7_LbWubptAdEyDhNnUdMV6iI';

export const ADD_DESTINATION = 'ADD_DESTINATION'
export const DELETE_DESTINATION = 'DELETE_DESTINATION'
export const SET_CURRENTLOCATION = 'SET_CURRENTLOCATION'
export const SET_MODAL_VISIBLE = 'SET_MODAL_VISIBLE'
export const SET_ROUTE_MODAL_VISIBLE = 'SET_ROUTE_MODAL_VISIBLE'